# Generated by Django 5.0.3 on 2024-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="allowed_domains",
            field=models.TextField(default="[]"),
        ),
    ]
