# Generated by Django 5.0.7 on 2024-08-02 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="subdomain",
        ),
    ]
