# Generated by Django 5.0.7 on 2024-08-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_institution_domain_and_more"),
        ("ai", "0002_campaign_campaignperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="extended_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="member",
            name="join_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MappingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mapping", models.JSONField()),
                ("is_default", models.BooleanField(default=False)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.institution",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "institution")},
            },
        ),
    ]
