# Generated by Django 5.0.7 on 2024-08-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_institution_domain_and_more"),
        ("ai", "0003_member_extended_data_member_join_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("email", "institution")},
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name="member",
            name="user",
        ),
    ]
