# Generated by Django 5.0.7 on 2024-08-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0004_alter_member_unique_together_alter_member_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="churn_probability",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="member",
            name="churn_risk",
            field=models.CharField(
                choices=[
                    ("low", "Low Risk"),
                    ("medium", "Medium Risk"),
                    ("high", "High Risk"),
                ],
                default="low",
                max_length=10,
            ),
        ),
    ]
